version: 2

defaults: &defaults
  working_directory: ~/qlik-smart-pivot
  docker:
    - image: circleci/node:stretch
  environment:
    GITHUB_ORG: "qlik-oss"
    GITHUB_REPO: "PLSmartPivot"
    PACKAGE_NAME: "qlik-smart-pivot"

jobs:
  test:
    docker:
    - image: circleci/node:stretch-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  bump-version:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Bump version
          command: scripts/bump-version.sh $GITHUB_ORG $GITHUB_REPO
      - persist_to_workspace:
          root: ~/qlik-smart-pivot
          paths:
            - BUMPED_VERSION

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qlik-smart-pivot
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build and package
          command: |
            export VERSION=$(scripts/get-bumped-version.sh)
            echo "Version: ${VERSION}"
            npm run build:zip
            sudo chmod +x scripts/verify-files.sh
            scripts/verify-files.sh
          environment:
            NODE_ENV: production
      - persist_to_workspace:
          root: ~/qlik-smart-pivot
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qlik-smart-pivot
      - run:
          name: Install ghr
          command: scripts/install-ghr.sh
      - run:
          name: Create GitHub Release
          command: |
            export VERSION=$(scripts/get-bumped-version.sh)
            echo "Version: ${VERSION}"
            scripts/create-release.sh $GITHUB_ORG $GITHUB_REPO $PACKAGE_NAME $VERSION

workflows:
  version: 2
  master_flow:
    jobs:
      - test
      - bump-version:
          requires:
            - test
      - build:
          requires:
            - bump-version
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
